/** IPC channel names shared by main and preload (single source of truth). */
export const CHANNELS = {
  connect: 'cgate:connect',
  disconnect: 'cgate:disconnect',
  getTree: 'cgate:getTree',
  status: 'cgate:status', // main -> renderer push
  state: 'cgate:state', // main -> renderer push
  sitesList: 'sites:list',
  sitesAdd: 'sites:add',
  sitesUpdate: 'sites:update',
  sitesRemove: 'sites:remove',
  sitesLabelsGet: 'sites:labels:get',
  sitesLabelsSave: 'sites:labels:save',
  sitesCanPersistPassword: 'sites:canPersistPassword',
  setLevel: 'control:setLevel',
  terminateRamp: 'control:terminateRamp',
  rename: 'labels:rename',
  clearTag: 'labels:clear',
  projectSave: 'project:save',
  projectName: 'project:name',
  projectDir: 'project:dir',
  projectList: 'project:list',
  projectLoad: 'project:load',
  projectStart: 'project:start',
  projectUse: 'project:use',
  netList: 'net:list',
  netOpen: 'net:open',
  netClose: 'net:close',
  netSync: 'net:sync',
  netHealth: 'net:health',
  activityLog: 'activity:list',
  activity: 'cgate:activity',
  projectImport: 'project:import',
  projectExport: 'project:export',
  inventoryExport: 'inventory:export',
  nodeDetail: 'nodes:detail',
  networkLevels: 'nodes:networkLevels',
  identifyUnit: 'nodes:identifyUnit',
  serverStatus: 'cgate:serverStatus',
  groupParams: 'nodes:groupParams',
  unitParams: 'nodes:unitParams',
  setGroupParam: 'nodes:setGroupParam',
  setUnitName: 'nodes:setUnitName',
  fireScene: 'control:fireScene',
  trigger: 'cgate:trigger',
  treeChanged: 'cgate:treeChanged',
  measurement: 'cgate:measurement',
  updateStatus: 'app:updateStatus',
  updateCheck: 'app:updateCheck',
  updateInstall: 'app:updateInstall',
} as const;

export type IpcChannel = (typeof CHANNELS)[keyof typeof CHANNELS];
